version: '3.8'

services:
  f1_app:
    build: .
    container_name: f1_predictor
    volumes:
      - ./app:/app
      - ./data:/data
      - ./model:/model
    ports:
      - "8501:8501"
    stdin_open: true
    tty: true
    command: tail -f /dev/null